-- =========================================================
-- Project 3: SQL Data Analysis
-- Decodelabs Data Analytics Internship
--
-- Objective:
-- Use SQL queries to extract insights from a transactional
-- sales dataset.
--
-- Skills Demonstrated:
-- - SELECT statements
-- - Filtering with WHERE
-- - Sorting with ORDER BY
-- - Grouping using GROUP BY
-- - Aggregations using COUNT, SUM, and AVG
--
-- Tool Used:
-- MySQL Workbench
-- =========================================================

-- Create a new database for the project
CREATE DATABASE decodelabs_sql_project;

-- Select the database for use
USE decodelabs_sql_project;

-- Creating a sales_data table
CREATE TABLE sales_data (
    OrderID VARCHAR(50),
    Date DATE,
    CustomerID VARCHAR(50),
    Product VARCHAR(50),
    Quantity INT,
    UnitPrice DECIMAL(10,2),
    ShippingAddress VARCHAR(50),
    PaymentMethod VARCHAR(50),
    OrderStatus VARCHAR(50),
    TrackingNumber VARCHAR(100),
    ItemsInCart INT,
    CouponCode VARCHAR(50),
    ReferralSource VARCHAR(50),
    TotalPrice DECIMAL(10,2),
    CalculatedTotal DECIMAL(10,2),
    Month INT
);

-- Viewing first 10 rows of the imported data
select *
from sales_data
limit 10;

-- Display selected columns from the dataset
SELECT OrderID, Product, Quantity, TotalPrice
FROM sales_data;

-- Retrieve orders paid using Online payment method
SELECT *
FROM sales_data
WHERE PaymentMethod = 'Online';

-- Retrieve orders with TotalPrice greater than 1000
SELECT OrderID, Product, TotalPrice
FROM sales_data
WHERE TotalPrice > 1000;

-- Retrieve orders with TotalPrice greater than 1000 and product is Monitor
SELECT OrderID, Product, TotalPrice
FROM sales_data
WHERE TotalPrice > 1000 and product="Monitor";

-- Sort products by TotalPrice in descending order
SELECT OrderID, Product, TotalPrice
FROM sales_data
ORDER BY TotalPrice DESC;

-- Sort products by Quantity in ascending order
SELECT OrderID, Product, Quantity
FROM sales_data
ORDER BY Quantity ASC;

-- Count the total number of orders

SELECT COUNT(*) AS Total_Orders
FROM sales_data;

-- Calculating the Total Revenue generated
select sum(totalprice) As Total_Revenue
from sales_data;

-- Calculate average transaction value
SELECT AVG(TotalPrice) AS Average_Order_Value
FROM sales_data;

-- Calculate total revenue generated by each product
SELECT Product,
       SUM(TotalPrice) AS Total_Revenue
FROM sales_data
GROUP BY Product;

-- Display products ranked by total revenue
SELECT Product,
       SUM(TotalPrice) AS Total_Revenue
FROM sales_data
GROUP BY Product
ORDER BY Total_Revenue DESC;

-- Count transactions by payment method
SELECT PaymentMethod,
       COUNT(*) AS Number_of_Transactions
FROM sales_data
GROUP BY PaymentMethod
order by Number_of_Transactions desc;

-- Count orders based on order status
SELECT OrderStatus,
       COUNT(*) AS Order_Count
FROM sales_data
GROUP BY OrderStatus
order by Order_Count desc;


-- =========================================================
-- Key Insights and Observations
-- =========================================================

-- 1. The dataset contains a large number of completed transactions,
--    indicating active customer purchasing activity.

-- 2. Products generated varying levels of revenue, with some
--    products significantly outperforming others in total sales.

-- 3. Online payment methods were frequently used, suggesting
--    strong customer preference for digital transactions.

-- 4. High-value transactions were identified when sorting by
--    TotalPrice, indicating the presence of premium or bulk purchases.

-- 5. Revenue analysis using SUM() helped identify the total
--    sales generated across all transactions.

-- 6. GROUP BY analysis provided useful insights into product
--    performance and transaction distribution across categories.

-- 7. Average transaction value analysis revealed moderate
--    customer spending behavior across the dataset.


-- =========================================================
-- Conclusion
-- =========================================================

-- This project demonstrated the use of fundamental SQL queries
-- to analyze a transactional sales dataset. Using SELECT,
-- WHERE, ORDER BY, GROUP BY, COUNT(), SUM(), and AVG(),
-- meaningful insights were extracted regarding customer
-- transactions, product performance, payment behavior,
-- and revenue trends.

-- The project strengthened practical SQL skills and reinforced
-- the importance of data querying and analysis in supporting
-- business decision-making.